# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test & Lint

on:
  push:
    branches:
      - "main"
      - "feature/*"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.13", "3.11.8", "3.12.10", "3.13.3"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
          python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-aiohttp pytest-asyncio pytest-cov pylint black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check with black
      run: |
        black --check ./custom_components/wiser_by_feller
